 server:
   port: 9000
 spring:
   application:
     name: zuul-gateway
 zuul:
 #不通过网关进行代理
  ignoredServices: '*'
  routes:
  #地址是/apigateway1/**地址时会转到product-service上
    product-service: /apigateway1/**
    order-service-feign-hystrix-dashbord: /apigateway2/**
 eureka:
   client:
     service-url:
      defaultZone: http://localhost:8761/eureka/


